"""create raw schema

Revision ID: 29582dd407eb
Revises: 
Create Date: 2026-03-24 21:33:50.393586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '29582dd407eb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE SCHEMA IF NOT EXISTS raw")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('event_name', sa.Text(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('promotion', sa.Text(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id'),
    schema='raw'
    )
    op.create_table('fighters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=True),
    sa.Column('first_name', sa.Text(), nullable=True),
    sa.Column('last_name', sa.Text(), nullable=True),
    sa.Column('nickname', sa.Text(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('height_cm', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('reach_cm', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('stance', sa.Text(), nullable=True),
    sa.Column('weight_class', sa.Text(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('draws', sa.Integer(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id'),
    schema='raw'
    )
    op.create_table('fights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Text(), nullable=False),
    sa.Column('event_source_id', sa.Text(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('fighter_1_source_id', sa.Text(), nullable=True),
    sa.Column('fighter_2_source_id', sa.Text(), nullable=True),
    sa.Column('fighter_1_id', sa.Integer(), nullable=True),
    sa.Column('fighter_2_id', sa.Integer(), nullable=True),
    sa.Column('winner_source_id', sa.Text(), nullable=True),
    sa.Column('winner_id', sa.Integer(), nullable=True),
    sa.Column('weight_class', sa.Text(), nullable=True),
    sa.Column('gender', sa.Text(), nullable=True),
    sa.Column('fight_order', sa.Integer(), nullable=True),
    sa.Column('scheduled_rounds', sa.Integer(), nullable=True),
    sa.Column('finish_round', sa.Integer(), nullable=True),
    sa.Column('finish_time_seconds', sa.Integer(), nullable=True),
    sa.Column('result_method', sa.Text(), nullable=True),
    sa.Column('result_details', sa.Text(), nullable=True),
    sa.Column('referee', sa.Text(), nullable=True),
    sa.Column('title_fight', sa.Boolean(), nullable=True),
    sa.Column('performance_bonus', sa.Boolean(), nullable=True),
    sa.Column('fight_of_the_night', sa.Boolean(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['raw.events.id'], ),
    sa.ForeignKeyConstraint(['fighter_1_id'], ['raw.fighters.id'], ),
    sa.ForeignKeyConstraint(['fighter_2_id'], ['raw.fighters.id'], ),
    sa.ForeignKeyConstraint(['winner_id'], ['raw.fighters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id'),
    schema='raw'
    )
    op.create_table('fight_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fight_id', sa.Integer(), nullable=False),
    sa.Column('fighter_id', sa.Integer(), nullable=False),
    sa.Column('knockdowns', sa.Integer(), nullable=True),
    sa.Column('sig_strikes_landed', sa.Integer(), nullable=True),
    sa.Column('sig_strikes_attempted', sa.Integer(), nullable=True),
    sa.Column('total_strikes_landed', sa.Integer(), nullable=True),
    sa.Column('total_strikes_attempted', sa.Integer(), nullable=True),
    sa.Column('takedowns_landed', sa.Integer(), nullable=True),
    sa.Column('takedowns_attempted', sa.Integer(), nullable=True),
    sa.Column('submissions_attempted', sa.Integer(), nullable=True),
    sa.Column('reversals', sa.Integer(), nullable=True),
    sa.Column('control_time_seconds', sa.Integer(), nullable=True),
    sa.Column('head_strikes_landed', sa.Integer(), nullable=True),
    sa.Column('head_strikes_attempted', sa.Integer(), nullable=True),
    sa.Column('body_strikes_landed', sa.Integer(), nullable=True),
    sa.Column('body_strikes_attempted', sa.Integer(), nullable=True),
    sa.Column('leg_strikes_landed', sa.Integer(), nullable=True),
    sa.Column('leg_strikes_attempted', sa.Integer(), nullable=True),
    sa.Column('distance_strikes_landed', sa.Integer(), nullable=True),
    sa.Column('distance_strikes_attempted', sa.Integer(), nullable=True),
    sa.Column('clinch_strikes_landed', sa.Integer(), nullable=True),
    sa.Column('clinch_strikes_attempted', sa.Integer(), nullable=True),
    sa.Column('ground_strikes_landed', sa.Integer(), nullable=True),
    sa.Column('ground_strikes_attempted', sa.Integer(), nullable=True),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fight_id'], ['raw.fights.id'], ),
    sa.ForeignKeyConstraint(['fighter_id'], ['raw.fighters.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fight_id', 'fighter_id'),
    schema='raw'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fight_stats', schema='raw')
    op.drop_table('fights', schema='raw')
    op.drop_table('fighters', schema='raw')
    op.drop_table('events', schema='raw')
    op.execute("DROP SCHEMA IF EXISTS raw")
    # ### end Alembic commands ###
